### PR TITLE
Add support for larger numbers (until 2699392)

### PR DESCRIPTION
**Pull request by mircea-pavel-anton**
Github has a file size limit of 100MB apparently, so I had to limit the support for numbers at 2699392. A technical limitation on their side, apparently.

However, we could split this into multiple files, to add support for even more numbers. I wrote a bit of code to generate such files that fly under their radar in terms of file size:

```python
import os


def get_file_size(path):
  """Returns the size of the file located at the given path in mebibytes"""
  stats = os.stat(path)
  return stats.st_size / (1024 * 1024)

file_name ="if_else.py"
file = open(file_name, "a")
index = 999999 + 1

while (get_file_size(file_name) < 99):
  file.write(f"  elif number == {index}: return {index % 2 == 0}\n")
  index = index + 1
```

Let me know what you think!

### CODE REVIEW

**Comment by mircea-pavel-anton** [comment]
Fixes #1

**Comment by LinusKay** [comment]
Thank you for your support on this project 🙏 together we wil make the code world more efficient and reliable than ever. 

Its a shame I could never post this program in its full form, with support up to 100,000,000, but you're right, GitHub does only support up to 100MB (cowardice).



Splitting the files was my next plan, thanks for making life easier.

**Comment by LinusKay** [comment]
Also wow!! automation!!! why did i never think of this?? this will save so much time, and make my hands hurt less typing all of the lines out manually.

**Comment by mircea-pavel-anton** [comment]
Always glad to help push innovation and the advancement of technology!

**Comment by mircea-pavel-anton** [comment]
You may want to LICENSE this code so that others don't steal it and use it for profit!

**Pull request merged**
